### PR TITLE
Add basic test and CI

### PR DESCRIPTION
**Pull request by jeffheifetz**

### CODE REVIEW

**Comment by jeffheifetz** [comment]
Blatantly stole test from https://github.com/feross/eslint-config-standard/blob/master/test/validate-config.js

**Comment by AerialX** [comment]
Is it just me or is the CI log completely empty..?

Looks good though, besides that. Is there anything else you need to add here or is it ready for merge?

**Comment by AerialX** [comment]
Tested locally, works well. Travis has acknowledged the log issues.

**Comment by jeffheifetz** [comment]
There is a reported outage on Travis affecting logs, hopefully it's still reporting results correctly.

I'm happy with it if you are

**Comment by AerialX** [comment]
Yeah, it appears to be. The logs have shown up now.

**Pull request merged**
